---
env:
  name: UAM-v0
  max_episode_steps: 500
  state_type: feature
  wrappers: []
  wrapper_kwargs: {}
  env_kwargs:
    N_agents: 14
    multi_policy: false
    communication:
    full_RL: true
    plain_reward: false
    w_goal: 2
    w_coll: 1.5
  info: ''
agent:
  LSTMRecTD3:
    tgt_noise: 0.2
    tgt_noise_clip: 0.5
    pol_upd_delay: 2
    history_length: 2
    use_past_actions: false
    num_obs_OS: 4
    num_obs_TS: 4
seed: 42
timesteps: 2_500_000
epoch_length: 5000
eval_episodes: 10
actor_weights:
critic_weights:
gamma: 0.99
tau: 0.001
net_struc_actor:
net_struc_critic:
optimizer: Adam
loss: MSELoss
lr_actor: 0.0001
lr_critic: 0.0001
buffer_length: 500_000
grad_rescale: false
grad_clip: false
act_start_step: 5000
upd_start_step: 5000
upd_every: 1
batch_size: 32
device: cpu
