---
env:
  name: UAM-v0
  max_episode_steps: 500
  state_type: feature
  wrappers: []
  wrapper_kwargs: {}
  env_kwargs:
    N_agents_max: 10
    multi_policy: true
    prio: false
    full_RL: true
    w_goal: 1
    w_coll: 1
  info: ''
agent:
  MATD3:
    tgt_noise: 0.2
    tgt_noise_clip: 0.5
    pol_upd_delay: 2
seed: 42
timesteps: 3_000_000
epoch_length: 5000
eval_episodes: 5
actor_weights:
critic_weights:
gamma: 0.99
tau: 0.001
net_struc_actor: [[128, 'relu'], [128, 'relu'], [128, 'relu'], 'tanh']
net_struc_critic: [[128, 'relu'], [128, 'relu'], [128, 'relu'], 'identity']
optimizer: Adam
loss: MSELoss
lr_actor: 0.0001
lr_critic: 0.0001
buffer_length: 500_000
grad_rescale: false
grad_clip: false
act_start_step: 5000
upd_start_step: 5000
upd_every: 1
batch_size: 32
device: cpu
